[DOC-11265] Updated Reserved Words list
couchbaselabs/docs-devex pull request #124
Opened 2024-02-09 05:13 UTC by julia-cb

Added the following to the reserved words list:

- DEFAULT
- LATERAL
- REPLACE
- VECTOR

Also had to move other words around to keep the table from breaking.

Jira ticket: https://issues.couchbase.com/browse/DOC-11265
Updated page: https://docs.couchbase.com/server/current/n1ql/n1ql-language-reference/reservedwords.html

2024-02-09 21:00 UTC, simon-dew requested changes
Thanks for doing this @julia-cb! Just a couple of changes in the ordering.

This PR meets the requirements of DOC-11265 as it is. I've gone through the SQL++ lexer and I think I've identified all the remaining reserved words that we need to add, as per comments on the ticket. We can add those to this PR or it in a later PR if you prefer?

2024-02-09 21:00 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/reservedwords.adoc
> +| REPLACE
Swap RESPECT and REPLACE to maintain alphabetical order

2024-02-09 21:00 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/reservedwords.adoc
> +| DEFAULT
Swap DEFAULT and DELETE to maintain alphabetical order

2024-02-09 21:00 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/reservedwords.adoc
> +| LAST
Swap LATERAL and LAST to maintain alphabetical order

2024-02-09 21:06 UTC, simon-dew commented
As noted on the JIRA issue, most of the remaining reserved words relate to sequences, so we could add those as part of DOC-11421.

2024-02-09 23:20 UTC, julia-cb commented
@simon-dew Thanks for the review Simon! I added the words you mentioned in your jira ticket comment, and removed SEMI. I'll wait to hear back from Donald on whether there's more words we need to add to the list :)

2024-02-12 13:27 UTC, simon-dew requested changes
Thanks for adding the rest of the restricted words @julia-cb ! I double-checked the list against [n1ql.nex](https://github.com/couchbase/query/blob/trinity/parser/n1ql/n1ql.nex) and I have some more comments. Some of them are my fault, I obviously can't read my own writing.

2024-02-12 13:27 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/reservedwords.adoc
> +| ROLES
`ROLES` shouldn't be here, sorry. Please delete. My bad, can't read my own writing.

2024-02-12 13:27 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/reservedwords.adoc
>  | MINUS
I know it was in the original file, but I don't think `MINUS` shouldn't be here either. Please delete.

2024-02-12 13:27 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/reservedwords.adoc
> +| PREVIEW
Sorry, this should be `PREVIOUS`, not <s>PREVIEW</s>. Again, my bad, can't read my own writing.

2024-02-12 13:27 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/reservedwords.adoc
> +| RECURSIVE
Please move `READ` between RAW and REALM, and move `RECURSIVE` between REALM and REDUCE.

2024-02-14 21:51 UTC, julia-cb commented
@simon-dew Thanks for the review again! I addressed all the changes you requested. Let me know if the PR is good to go now :)

2024-02-14 21:55 UTC, simon-dew approved these changes
All comments updated, LGTM 👍

2024-02-14 23:33 UTC, merged