[DOC-10638] Add LATERAL keyword support
couchbaselabs/docs-devex pull request #125
Opened 2024-02-09 20:16 UTC by julia-cb

Adding LATERAL keyword support to ANSI JOIN, ANSI NEST, and Comma-Separated Join.

Jira ticket: https://issues.couchbase.com/browse/DOC-10638

Preview doc pages:

- [JOIN Clause](https://preview.docs-test.couchbase.com/lateralkeyword2/server/current/n1ql/n1ql-language-reference/join.html)
- [NEST Clause](https://preview.docs-test.couchbase.com/lateralkeyword2/server/current/n1ql/n1ql-language-reference/nest.html)
- [Comma-Separated Join](https://preview.docs-test.couchbase.com/lateralkeyword2/server/current/n1ql/n1ql-language-reference/comma.html)

----///----

Changes in this PR:

- [ANSI JOIN](https://docs.couchbase.com/server/current/n1ql/n1ql-language-reference/join.html#section_ek1_jnx_1db)
   - Added new section on LATERAL Joins
   - Added new LATERAL example
   - Updated ansi-join-clause ebnf file and diagram to include LATERAL
   - Created ansi-join-lateral n1ql and jsonc files for LATERAL example
 
- [ANSI NEST](https://docs.couchbase.com/server/current/n1ql/n1ql-language-reference/nest.html#section_tc1_nnx_1db)
   - Added new section on LATERAL Nest
   - Added new LATERAL example
   - Updated ansi-nest-clause ebnf file and diagram to include LATERAL
   - Created ansi-nest-lateral n1ql and jsonc files for LATERAL example

- [Comma-Separated Join](https://docs.couchbase.com/server/current/n1ql/n1ql-language-reference/comma.html)
   - Added new section on LATERAL Join
   - Added LATERAL query to existing "Cartesian product" example (Example 1)
   - Updated comma-separated-join ebnf file and diagram to include LATERAL

2024-02-12 15:23 UTC, simon-dew requested changes
Good start! Comments to keep you on the right track

2024-02-12 15:23 UTC, simon-dew commented on modules/n1ql/partials/grammar/dql.ebnf
> +ansi-join-clause ::= ansi-join-type? 'JOIN LATERAL' ansi-join-rhs ansi-join-predicate
Good start! 'JOIN' is mandatory in the JOIN clause, but 'LATERAL' is optional, so these two tokens need to be separate, and the LATERAL keyword needs to be marked as optional with a question mark:

```suggestion
ansi-join-clause ::= ansi-join-type? 'JOIN' 'LATERAL'? ansi-join-rhs ansi-join-predicate
```

2024-02-12 15:23 UTC, simon-dew commented on modules/n1ql/examples/select/ansi-join-cover.n1ql
> +FROM airport JOIN LATERAL route ON route.sourceairport = airport.faa
We shouldn't add the LATERAL keyword to the existing examples, because it strongly implies that LATERAL is mandatory, when it is (a) optional and (b) doesn't do anything.

Instead we should add a single new example, which is exactly the same as one of the existing examples (*), but with the inclusion of the LATERAL keyword. The new example would point out that the results of the new example are exactly the same.

(*) I would suggest `ansi-join-inner.n1ql`

2024-02-12 15:23 UTC, simon-dew commented on modules/n1ql/examples/select/ansi-join-inner.n1ql
> +INNER JOIN LATERAL airline
Revert (as per previous comment)

2024-02-12 15:23 UTC, simon-dew commented on modules/n1ql/examples/select/ansi-join-left.n1ql
> +LEFT JOIN LATERAL landmark lmark -- <.>
Revert (as per previous comment)

2024-02-12 15:23 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/join.adoc
> +JOIN LATERAL airline
Revert (as per previous comment)

2024-02-12 15:23 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/join.adoc
> +LEFT JOIN LATERAL airline
Revert (as per previous comment)

2024-02-12 15:23 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/join.adoc
> +* INNER joins and LEFT OUTER joins support the LATERAL keyword in front of the right-hand side keyspace. RIGHT OUTER joins do not support the LATERAL keyword.
Good start on the description, but this is a new keyword, not a limitation, so I don't think it belongs in this section. We aim to describe the keywords (as far as possible) in the order they appear in the syntax summary. So there should be a new heading 4 section called something like `==== LATERAL Joins` between the sections on Join Type and Join Predicate &mdash; i.e. starting at line 148 above.

2024-02-12 19:00 UTC, julia-cb commented
@simon-dew Thanks for the feedback both here and over zoom, Simon! I updated the JOIN page with your feedback (and was even able to update the ansi-join-clause image!). I'll update the NEST and Comma pages with the LATERAL info and add it to the this PR :)

2024-02-15 21:38 UTC, julia-cb commented
@simon-dew Hi Simon, this is ready for a review whenever you have a moment! Thank you :)

2024-02-22 17:05 UTC, simon-dew requested changes
Hi @julia-cb ! Thanks for your updates and accurate examples. The only thing was, I don't think they fully explained why a developer would want to use this feature. I went back to the feature PRD to look at the use cases that they were focused on. I've made suggestions in the following areas:

1. Suggested improved wording to explain what the feature is for.
2. Suggested example for comma-separated joins, based on the PRD.
3. Notes about the impact on query optimization, also taken from the PRD.
4. Other minor changes.

Unfortunately this makes it look as if I've completely ripped it to shreds again. I am sorry about that!

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/join.adoc
> +This makes Couchbase queries compatible with queries from relational databases.
May seem paradoxical, but I think this needs more information on what this keyword is for and why you would want use it. Even though it doesn't do anything. Something like:

```suggestion
When an expression on the right-hand side of an ANSI join references a keyspace that is already specified in the same FROM clause, the expression is said to be correlated.
In relational databases, a join which contains correlated expressions is referred to as a lateral join.
In {sqlpp}, lateral correlations are detected automatically, and there is no need to specify that a join is lateral.

In Couchbase Server 7.6 and later, you can use the LATERAL keyword as a visual reminder that a join contains correlated expressions.
The LATERAL keyword is not required -- the keyword is included solely for compatibility with queries from relational databases.

If you use the LATERAL keyword in a join that has no lateral correlation, the keyword is ignored.
```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/join.adoc
> +ansi-join-lateral:: <<ansi-join-lateral>> icon:caret-down[]
Delete this line: there's no element in the syntax diagram called `ansi-join-lateral`

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/join.adoc
> +[#ANSI-Join-Example-4]
Revert this. As a general rule I don't change IDs within a topic: you never know what might be linking to them.

```suggestion
[#ANSI-Join-Example-3]
```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/join.adoc
> +.RIGHT OUTER JOIN of <<ANSI-Join-Example-3>>
Revert this, as above.

```suggestion
.RIGHT OUTER JOIN of <<ANSI-Join-Example-2>>
```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/join.adoc
> +[#ANSI-Join-Example-5]
Revert this, as above.

```suggestion
[#ANSI-Join-Example-4]
```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/join.adoc
>  [#ANSI-Join-Example-2]
Give the new example a new ID

```suggestion
[#ANSI-Join-Example-1A]
```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/join.adoc
> +[#ANSI-Join-Example-3]
Revert this, so the existing example keeps the same ID

```suggestion
[#ANSI-Join-Example-2]
```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/comma.adoc
> +This makes Couchbase queries compatible with queries from relational databases.
more information on what this keyword is for and why you would want use it

```suggestion
When an expression on the right-hand side of a comma-separated join references a keyspace that is already specified in the same FROM clause, the expression is said to be correlated.
In relational databases, a join which contains correlated expressions is referred to as a lateral join.
In {sqlpp}, lateral correlations are detected automatically, and there is no need to specify that a join is lateral.

In Couchbase Server 7.6 and later, you can use the LATERAL keyword as a visual reminder that a join contains correlated expressions.
The LATERAL keyword is not required -- the keyword is included solely for compatibility with queries from relational databases.

If you use the LATERAL keyword in a join that has no lateral correlation, the keyword is ignored.
```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/nest.adoc
> +This makes Couchbase queries compatible with queries from relational databases.
more information on what this keyword is for and why you would want use it

```suggestion
When an expression on the right-hand side of an ANSI nest references a keyspace that is already specified in the same FROM clause, the expression is said to be correlated.
In relational databases, a join which contains correlated expressions is referred to as a lateral join.
In {sqlpp}, lateral correlations are detected automatically, and there is no need to specify that a nest or join is lateral.

In Couchbase Server 7.6 and later, you can use the LATERAL keyword as a visual reminder that a nest contains correlated expressions.
The LATERAL keyword is not required -- the keyword is included solely for compatibility with queries from relational databases.

If you use the LATERAL keyword in a nest that has no lateral correlation, the keyword is ignored.
```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/nest.adoc
> +[#ANSI-NEST-Example-3]
Revert this -- keep existing IDs the same

```suggestion
[#ANSI-NEST-Example-2]
```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/nest.adoc
>  [#ANSI-NEST-Example-2]
Use a new ID for the new example

```suggestion
[#ANSI-NEST-Example-1A]
```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/comma.adoc
> +Compare the queries above with the following query using an ANSI join.
Based on the importance given to comma-separated joins with subqueries in the PRD, I think we need to have a separate example for LATERAL with comma-separated joins. Revert this change, and let's add a separate example at the end of this section.

```suggestion
Compare the query above with the following query using an ANSI join.
```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/comma.adoc
> +The results of the three queries are the same.
Revert this, as above

```suggestion
The results of the two queries are the same.
```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/comma.adoc
At the end of this page, add a new example as follows:

```asciidoc
[#example-lateral]
.Lateral correlation
====
The following query has a lateral correlation between the subquery and the `airport` keyspace.

.Comma-separated join
[source,sqlpp]
----
SELECT airport.airportname, t2.name
FROM airport,
(SELECT name FROM hotel WHERE hotel.city = airport.city) AS t2
LIMIT 5;
----

Compare the query above with the following query using the LATERAL keyword.

.Comma-separated join with LATERAL keyword
[source,sqlpp]
----
SELECT airport.airportname, t2.name
FROM airport,
LATERAL (SELECT name FROM hotel WHERE hotel.city = airport.city) AS t2
LIMIT 5;
----

The results of the two queries are the same.

.Results
[source,json]
----
[
  {
    "airportname": "Mandelieu",
    "name": "Hotel Cybelle"
  },
  {
    "airportname": "Cote D\\'Azur",
    "name": "Best Western Hotel Riviera Nice"
  },
  {
    "airportname": "Cote D\\'Azur",
    "name": "Hotel Anis"
  },
  {
    "airportname": "Cote D\\'Azur",
    "name": "NH Nice"
  },
  {
    "airportname": "Cote D\\'Azur",
    "name": "Hotel Suisse"
  }
]
----
====
```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/comma.adoc
> +==== LATERAL Join
In this page, this needs to be a level 3 heading. (This page doesn't have the extra level of ANSI / Lookup / Index that the JOIN and NEST pages do.)

```suggestion
=== LATERAL Join
```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/examples/select/ansi-join-lateral.n1ql
This example works, but it only illustrates how the LATERAL keyword is ignored if there is no correlation between the left-hand side and the right-hand side of the join. Can you ask @miaobingjie or the SQL++ team if there is an example of an ANSI join with correlation between the left-hand side and the right-hand side of the join, so we can show the LATERAL keyword in the relevant environment?

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/examples/select/ansi-join-lateral.jsonc
May need to update this. See comments on `ansi-join-lateral.n1ql`.

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/examples/select/ansi-nest-lateral.n1ql
This example works, but it only illustrates how the LATERAL keyword is ignored if there is no correlation between the left-hand side and the right-hand side of the nest. Can you ask @miaobingjie or the SQL++ team if there is an example of an ANSI nest with correlation between the left-hand side and the right-hand side of the nest, so we can show the LATERAL keyword in the relevant environment?

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/examples/select/ansi-nest-lateral.jsonc
May need to update this. See comments on `ansi-nest-lateral.n1ql`.

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/join.adoc
> +
Add a note at the end here:

```asciidoc
NOTE: Using the LATERAL keyword in an ANSI join implies that the right-hand side of the join must appear after the left-hand side of the join.
This may prevent the cost-based optimizer from reordering joins in the query to give the optimal join order.
For details, see xref:n1ql:n1ql-language-reference/cost-based-optimizer.adoc#join-enumeration[Join Enumeration].
```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/comma.adoc
> +
Add a note at the end here:

```asciidoc
NOTE: Using the LATERAL keyword in a comma-separated join implies that the right-hand side of the join must appear after the left-hand side of the join.
This may prevent the cost-based optimizer from reordering joins in the query to give the optimal join order.
For details, see xref:n1ql:n1ql-language-reference/cost-based-optimizer.adoc#join-enumeration[Join Enumeration].
```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/comma.adoc
> +
Standard boilerplate text for new feature

```suggestion

ifeval::['{page-component-version}' == '7.6']
_(Introduced in Couchbase Server 7.6)_
endif::[]

```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/join.adoc
> +
Standard boilerplate text for new feature

```suggestion

ifeval::['{page-component-version}' == '7.6']
_(Introduced in Couchbase Server 7.6)_
endif::[]

```

2024-02-22 17:05 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/nest.adoc
> +
Standard boilerplate text for new feature

```suggestion

ifeval::['{page-component-version}' == '7.6']
_(Introduced in Couchbase Server 7.6)_
endif::[]

```

2024-02-22 17:20 UTC, simon-dew commented
When we're finished with peer review, please add @miaobingjie as an SME reviewer (as the person who raised the original ticket)

2024-02-28 23:29 UTC, julia-cb commented
@simon-dew Thanks Simon! Great feedback and I applied all of it. I reached out to Bingjie about the n1ql files and will update the docs again when he replies.

2024-03-04 23:59 UTC, julia-cb commented
@simon-dew Hey Simon, let me know if this PR is good to be merged (Bingjie already provided the code examples over slack so I'm not sure a thorough review from him is necessary).

2024-03-05 12:10 UTC, simon-dew approved these changes
LGTM 👍 let's get it merged, and if there are any pernickety changes we can fix them later.

2024-03-05 17:23 UTC, merged