[DOC-11277] Document FORMALIZE miscellaneous function
couchbaselabs/docs-devex pull request #128
Opened 2024-02-15 00:32 UTC by julia-cb

Jira ticket: [DOC-11277](https://issues.couchbase.com/browse/DOC-11277)

Page affected: [Miscellaneous Utility Functions](https://docs.couchbase.com/server/current/n1ql/n1ql-language-reference/metafun.html)

Changes in this PR:

- Added section on FORMALIZE(`statement` [ `,query_context` ]) to miscellaneous functions page.

(Please ignore the Eventing page that was deleted!! I ended up pushing an Eventing change by accident and couldn't figure out how to remove it from the PR without deleting the file and re-pushing the changes. Git is confusing sometimes 😵‍💫)

2024-02-15 15:29 UTC, lamagnifica commented on modules/n1ql/pages/n1ql-language-reference/metafun.adoc
> +Can be spelled as FORMALIZE or FORMALISE.
fragments ok?

2024-02-15 15:29 UTC, lamagnifica commented on modules/n1ql/pages/n1ql-language-reference/metafun.adoc
> +SELECT FORMALIZE("select * from c1","default: example")
is there a way to do use the travel-sample.inventory data to show this? without knowing the background of what needs to be formalized, seeing the result doesn't really help

2024-02-16 15:31 UTC, julia-cb commented on modules/n1ql/pages/n1ql-language-reference/metafun.adoc
> +SELECT FORMALIZE("select * from c1","default: example")
Good question - I'll update the example to use the travel-sample data!

2024-02-22 17:38 UTC, simon-dew requested changes
Brilliant. Just a few minor changes.

2024-02-22 17:38 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/metafun.adoc
> +
Standard boilerplate text for new feature

```asciidoc

ifeval::['{page-component-version}' == '7.6']
_(Introduced in Couchbase Server 7.6)_
endif::[]

```

2024-02-22 17:38 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/metafun.adoc
> +Specifies all references from a query.
Looking for slightly more descriptive wording here. Something like

```suggestion
Fully expands all references within a query, using the specified query context.
```

2024-02-22 17:38 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/metafun.adoc
> +Can be spelled as FORMALIZE or FORMALISE.
```suggestion
This function has a synonym FORMALISE().
```

Check UNNEST_POS and UNNEST_POSITION in this document to see how synonyms are handled.

2024-02-22 17:38 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/metafun.adoc
> +====
As there's more than one example for FORMALIZE(), let's give the example a title

```suggestion
[[formalize-ex1,FORMALIZE() Example 1]]
.Formalize a query
====
```

2024-02-22 17:38 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/metafun.adoc
> +====
And let's give this example an ID and a title too

```suggestion
[[formalize-ex2,FORMALIZE() Example 2]]
.Formalize recently completed requests
====
```

2024-02-22 17:38 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/metafun.adoc
> +  ...
I know it's not standard JSON but I usually add a JSON-C comment marker for ellipses within a JSON file

```suggestion
  // ...
```

2024-02-22 17:38 UTC, simon-dew commented on modules/n1ql/pages/n1ql-language-reference/metafun.adoc
> +FROM system:completed_requests;
Looks kind of odd having the commas at the start of the line. Reads better if they're at the end of the previous line.

```suggestion
SELECT statement,
       NVL(queryContext,"") AS queryContext,
       formalize(statement, queryContext) AS formalized 
FROM system:completed_requests;
```

2024-02-22 17:39 UTC, simon-dew commented
When we're finished with peer review, please add @dhaggart for SME review, as the person who raised the original issue.

2024-02-22 18:40 UTC, julia-cb commented
@dhaggart Hi Donald, I added the new FORMALIZE function to the docs. Please take a quick look and review when you have a sec! Thanks :)

2024-02-23 11:24 UTC, dhaggart requested changes

2024-02-23 11:24 UTC, dhaggart commented on modules/n1ql/pages/n1ql-language-reference/metafun.adoc
> +    "statement": "advise SELECT *\nFROM route\nJOIN LATERAL airline\nON route.airlineid = META(airline).id\nWHERE route.sourceairport = \"SFO\";",
I'd avoid using an "advise" statement in the example.  I'd also pick one where we're actually seeing be transformed.

2024-02-23 17:27 UTC, julia-cb commented on modules/n1ql/pages/n1ql-language-reference/metafun.adoc
> +    "statement": "advise SELECT *\nFROM route\nJOIN LATERAL airline\nON route.airlineid = META(airline).id\nWHERE route.sourceairport = \"SFO\";",
Got it - I updated the example with the results you sent me over slack. Let me know if that's better!

2024-02-23 17:27 UTC, dhaggart approved these changes

2024-02-23 17:28 UTC, merged