AV-84193
couchbaselabs/docs-devex pull request #267
Opened 2024-09-03 14:30 UTC by simon-dew

This PR changes database to cluster in the devex docs. I've followed these rules, more or less, in descending order of priority:

* If the term is "cluster" in the UI, change to cluster
* If we're talking about the architecture of a deployment (e.g. "a node in the database"), change to cluster
* If it says "database" in the equivalent server page, keep as database
* If it's a generic term, e.g. "a relational database", keep as database
* If referring to the generic set of data rather than the architecture of a deployment (e.g. "a document in the database"), keep as database

I have tried not to make any changes to example files, diagram files, or dotted (hidden) adoc files.

Also removed one link to the Get Capella Host Name page, which is now hidden.

2024-09-03 15:24 UTC, bfavini approved these changes
This all looks fine...at some point, we may want or need to revisit to see whether we need to add the "operational" qualifier (Capella operational cluster...) But this is fine at this point.

2024-09-03 20:18 UTC, sarahlwelton requested changes
You ended up breaking one of the links :) Please fix!

2024-09-03 20:18 UTC, sarahlwelton commented on modules/search/pages/create-custom-analyzer.adoc
> +For more information about how to change Services on your cluster, see xref:cloud:clusters:modify-cluster.adoc[].
```suggestion
For more information about how to change Services on your cluster, see xref:cloud:clusters:modify-database.adoc[].
```

2024-09-04 10:47 UTC, simon-dew commented on modules/search/pages/create-custom-analyzer.adoc
> +For more information about how to change Services on your cluster, see xref:cloud:clusters:modify-cluster.adoc[].
D'oh!

2024-09-04 15:14 UTC, RichardSmedley approved these changes
:+1:

2024-09-04 16:24 UTC, dgnicholson approved these changes
Took a quick look through with a focus on the usage of "Operational Clusters" and it seems consistent with how we're using in `docs-capella`. ✅

2024-09-04 17:12 UTC, merged