[DOC-12610]: document `nprobe` tweaking
couchbaselabs/docs-devex pull request #281
Opened 2024-10-28 12:32 UTC by RayOffiah

New page on fine-tuning the vector search.

2024-11-06 15:45 UTC, sarahlwelton requested changes
Lot of noise in this PR with just deleting so many end-of-line spaces. I also have some concerns about how this is shaping up right now. Let me know if you want to discuss.

2024-11-06 15:45 UTC, sarahlwelton commented on modules/tutorials/partials/diagrams/couchbase-hierarchy.puml
Did this need to be included in this PR?

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/partials/nav.adoc
> +** xref:7.6@server:vector-search:fine-tune-vector-search.adoc[]
I would move this below all of the Run a Vector Search pages in the TOC, personally.

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> += Fine-tuning Vector Searches
```suggestion
= Fine-Tuning a Vector Search Query
```

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +:description: pass:q[Additional parameters can be added to a vector search REST call that will allow you to tune the search for recall and/or accuracy.]
```suggestion
:description: Add additional parameters to a Vector Search REST API call to tune the search for recall or accuracy.
```

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +:page-topic-type: concept
I'm not sure that this counts as a conceptual page.

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +== Overview
If you're not linking to this from elsewhere, this isn't a useful heading. 

```suggestion

```

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +This tuning occurs during indexing and querying, eliminating the need for users to adjust optimization parameters manually.
```suggestion
The Search Service automatically tunes your Vector Search indexes to achieve a balance between: 

* Recall, or the quality of your search results
* Latency, or your search response time
* Memory efficiency

This tuning occurs during indexing and querying. 
You do not need to adjust these parameters manually. 
```

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +Couchbase dynamically adjusts two critical vector parameters:
```suggestion
Specifically, the Search Service dynamically adjusts two critical vector parameters:
```

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +`nlist` (or `Centroid` count)::
```suggestion
`nlist`, also known as `Centroid` count::
```

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +The centroids are used to quickly find the surrounding closest matches in the index. Increasing the number of centroids will increase accuracy but will decrease the speed of the search.
```suggestion
Centroids are used to quickly find the surrounding closest matches in the Vector Search index. 
Increasing the number of centroids will increase accuracy but will decrease the speed of the search.
```
Remember to use ventilated prose, please.

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +The `nlist` is determined dynamically based on the size of the dataset (number of vectors) in a partition:
```suggestion
The `nlist` is determined dynamically based on the size of the dataset, or the number of vectors in a partition:
```

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +| stem:[4 xx sqrt("nvec")]
Can you build a preview site, please? I want to see how this renders in the table.

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +| For number of vectors less than 1000, Couchbase will carry out a straight forward one-to-one mapping between IDs and vectors with an exact vector comparison.
```suggestion
| For a number of vectors less than 1000, the Search Service will carry out a straight forward one-to-one mapping between IDs and vectors with an exact vector comparison.
```

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +The number of `centroids` that a query will check for similar vectors.
```suggestion
The number of `centroids` that a Search query will check for similar vectors.
```

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +The `nprobe` value is only set when Couchbase is using an Inverted File Index. Couchbase will select the best index type and comparison method depending on the size of the dataset and the `vector_ind
```suggestion
The `nprobe` value is only set when the Search Service is using an Inverted File Index. The Search Service will select the best index type and comparison method depending on the size of the dataset and your `vector_index_optimized_for` setting.
```
Please add a link to where we explain the `vector_index_optimized_for` setting. I know it's discussed in creation topics.

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +The Vector Search API will accept an additional parameter object, allowing for tuning the recall and/or accuracy of the search execution.
```suggestion
Add an additional parameter object to any Vector Search query to tune the recall or accuracy of your search.
```

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +The default value for this is 100, and the value represents the percentage of `centroids` that will be visited during a search. Reducing the value reduces the number of centroids visited, which will
```suggestion
You can add the following parameters to your query: 

`ivf_nprobe_pct`::
Adjusts the number percentage of clusters searched during queries, allowing for fine-tuning of the balance between recall and performance.
If the value of `nprobe` is 5% of `nlist` (the centroid count), then setting the value of `ivf_nprobe_pct` higher than 5% will have the search cover a higher percentage of clusters, which will improve the accuracy of the search.

`ivf_max_codes_pct`::
The default value for this is 100, and the value represents the percentage of `centroids` that will be visited during a search. 
Reducing the value reduces the number of centroids visited, which will decrease accuracy and recall, but will result in faster compute times.
```

These need to be added to the full Search documentation, with the explanation of all of the Search request parameters: https://docs.couchbase.com/cloud/search/search-request-params.html

If you don't feel up to doing that yourself, please log a ticket and I will pick it up.

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +For example, given a cluster `vector_index_optimized_for`: "recall" and `indexPartitions`: 5,  `nlist` and `nprobe` are determined based on the current vector count in a given partition:
```suggestion
== Example: nlist and nprobe Calculations on a Vector Search Index Set to Recall 

For example, if you had a Vector Search index with `vector_index_optimized_for` set to `"recall"` and `indexPartitions` set to `5`,  `nlist` and `nprobe` are determined based on the current vector count in a given partition:
```

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +----
How does this sample code relate to what's in the table above? The values provided are completely different from what you show in the calculation. What is this doing?

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/run-vector-search-ui.adoc
> +For more information about how the Search Service scores documents in search results, see xref:fts:fts-scoring.adoc[Scoring for Search Queries].
```suggestion
For more information about how the Search Service scores documents in search results, see xref:search:run-searches.adoc#scoring[Scoring for Search Queries].
```

Wrong link. Please don't link to old search doc.

2024-11-06 15:45 UTC, sarahlwelton commented on modules/vector-search/pages/run-vector-search-sdk.adoc
> +For more information about how the Search Service scores documents in search results, see xref:fts:fts-scoring.adoc[Scoring for Search Queries].
```suggestion
For more information about how the Search Service scores documents in search results, see xref:search:run-searches.adoc#scoring[Scoring for Search Queries].
```
Wrong link. Please don't link to old search doc.

2024-11-09 12:58 UTC, RayOffiah commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +| stem:[4 xx sqrt("nvec")]
Yup, can do that.

https://preview.docs-test.couchbase.com/doc-12610/server/current/vector-search/fine-tune-vector-search.html

2024-11-09 13:02 UTC, RayOffiah commented on modules/tutorials/partials/diagrams/couchbase-hierarchy.puml
I'll move it to a separate fix.

2024-11-15 16:03 UTC, sarahlwelton reviewed
Sorry, I'm being really picky but this is definitely shaping up really well :) Thanks for taking this on, Ray!

2024-11-15 16:03 UTC, sarahlwelton commented on modules/search/pages/search-index-params.adoc
> +|[#vector-index-optimized-param]#vector_index_optimized_for# |String |Vector Only a|
Why did we add the multiple hashes around this? I didn't think we needed to do that for table entries.

2024-11-15 16:03 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +(For more information on the `vector_index_optimized_for` setting, see  xref:search:search-index-params.adoc#vector-index-optimized-param[Search Index JSON properties ])
```suggestion
For more information on the `vector_index_optimized_for` setting, see  xref:search:search-index-params.adoc#vector-index-optimized-param[Search Index JSON properties].
```

2024-11-15 16:03 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +The cluster maintains two dynamically adjusted parameters that will affect the speed, accuracy, and resources used during the search:
```suggestion
The cluster maintains two dynamically adjusted parameters that will affect the speed, accuracy, and resources used during a search: 
```

2024-11-15 16:03 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +In the example above, the search will be carried out across all the fields, looking for close matches for the numbers specified in `vector`.
```suggestion
In the preceding example, the Search request returns results from any available fields in the index, but specifically searches the `embedding` field for the `10` closest matches to the vector `[0.024901132253900747, 1535]`.
```

2024-11-15 16:18 UTC, sarahlwelton requested changes
Sorry, actually saw the example you took this from. It's wrong in its current state. Please add this to the fixes, too.

2024-11-15 16:18 UTC, sarahlwelton commented on modules/vector-search/pages/fine-tune-vector-search.adoc
> +    "vector": [0.024901132253900747, 1535]
```suggestion
    "vector": [0.024901132253900747, . . .]
```

2024-11-18 15:12 UTC, sarahlwelton approved these changes
Thanks @RayOffiah!

2024-11-18 20:13 UTC, merged